### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#104]
Does Bootique have vision of it's 1.0?

**Comment by andrus** [comment]
Perhaps we can take this to the forum to let others chime in, but I can comment here. 1.0 vision is an open one. The initial plan was to build a minimal feature set and get the product out there (something that we did successfully) and then collect feedback and keep iterating (something that we are doing now).  Bootique and the modules keep maturing, and this is an incremental process.

I have a feeling that we are actually approaching 1.0, though are not 100% there yet. Currently I'd like to finish another addition to the metadata layer that would allow to inspect configuration structures, and then review it again.

**Comment by andrus** [comment]
I think we are on the verge of 1.0 now. The functionality that we have looks great. And we are even planning [2.0 feature](https://github.com/bootique/bootique-di) now. So closing this general request task.
