### ISSUE TITLE
Launching a daemon with access to DI-managed objects on application startup

### ISSUE THREAD

**Issue by atomashpolskiy** [bootique/bootique#106]
Hi @andrus , I want to launch a daemon thread on application startup, and I don't want to encapsulate it into a service (it doesn't have a public API). The caveat is that this daemon should have access to Guice-managed services. It seems to me that currently the two options would be:
1) to manually create `BQRuntime` and reproduce `io.bootique.Bootique#run()` in my code
2) to create a custom `Bootique` class and to override one of its protected methods (e.g. `io.bootique.Bootique#createRuntime(com.google.inject.Injector)`) to get direct access to the Injector. Also this would be my only option if I needed something that is described by Key/TypeLiteral, because BQRuntime only lets you get service instances.

Both options are not very convenient and (1) has a drawback. So I thought I might propose:
1) adding a static `Bootique.run(BQRuntime)` method, which will run the provided runtime in "default" Bootique way
2) adding a `BQRuntime.getInjector():Injector` method (I personally don't need it atm, but potentially it can be quite useful)

My code will look like this:
```java
BQRuntime runtime = Bootique.app(args).autoLoadModules().createRuntime();
Injector injector = runtime.getInjector();
// do stuff
Bootique.run(runtime);
```

**Comment by andrus** [comment]
You can write a custom Command object.

**Comment by atomashpolskiy** [comment]
I already have a command, it's Jetty's `ServerCommand`

**Comment by andrus** [comment]
What about an eager-loaded DI object?

**Comment by atomashpolskiy** [comment]
As far as I know, Guice doesn't provide a way to explicitly "eager load" anything; eagerness is determined by the Stage in which a given Injector is created

**Comment by andrus** [comment]
No , actually this should work under any stage configuration: https://github.com/google/guice/wiki/Scopes#eager-singletons

**Comment by andrus** [comment]
In light of discovery of [this Guice problem](https://github.com/google/guice/issues/1083) , is this task still an issue?

**Comment by atomashpolskiy** [comment]
I still think that adding a `BQRuntime.getInjector()` or some other means to retrieve objects by Key/TypeLiteral would be beneficial. Other than that, `asEagerSingleton()` was sufficient to solve my original problem.

**Comment by andrus** [comment]
Sure, let's discuss specific APIs in dedicated tasks.
