### ISSUE TITLE
Way to override JacksonService

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#108]
I'd like to change implementation of `JacksonService`. I want to do it, because it's only way to pass modules to jackson's `ObjectMapper` which used for config parsing.

**Comment by andrus** [comment]
Any specifics? You mean like adding "contribute" methods to BQCoreModule?

**Comment by IRus** [comment]
Motivation: to support kotlin data classes in config factories i need to register jackson kotlin module in `ObjectMapper`.

> You mean like adding "contribute" methods to BQCoreModule?

Yep, it can be done with this approach.

**Comment by andrus** [comment]
Still undecided on exposing even more of Jackson APIs in the Bootique core. An alternative solution to integrating Kotlin would be creating `bootique-kotlin` module that overrides `JacksonService` with its own subclass of `DefaultJacksonService`. Not as clean as contribution, but should work never the less.

**Comment by IRus** [comment]
I'm found that our jackson configuration (or jackson itself) doesn't support references, for example:

```
- step: &id001
    instrument:      Lasik 2000
    pulseEnergy:     5.0
    pulseDuration:   10
    repetition:      500
    spotSize:        2mm
- step: *id001                   # refers to the first step (with anchor &id001)
```

So i'm thinking about contributing `ConfigurationFactory` itself. It can be `EtcdConfigurationFactory`, `GroovyConfigurationFactory`, `KotlinScriptConfigurationFactory`, etc.

**Comment by andrus** [comment]
Interesting point on references. I think we need a separate bug report on this

**Comment by IRus** [comment]
Bootique provide ability to override module:

```kotlin
fun Bootique.withKotlinConfig(): Bootique {
    return this.override(BQCoreModule::class.java)
        .with(KotlinConfigModule::class.java)
}
```
