### ISSUE TITLE
Environment variables not merged into configuration

### ISSUE THREAD

**Issue by atomashpolskiy** [bootique/bootique#133]
Consider that we have the following `ServiceFactory` in `MyModule`:
```java
public class ServiceFactory {
  private boolean foo = true;
  // .. getter and setter
}
```

`ServiceFactory#foo` is `true` by default, and it's the only configurable option in `MyModule`, so we don't specify anything in YAML config.

Then, we set an environment variable `BQ_MY_FOO` to `false`.

Currently the override won't happen, and `ServiceFactory#foo` will remain `true`.
I suspect this is because of the following:
1) `io.bootique.config.jackson.InPlaceMapOverrider` puts `MY.FOO` into the aggregate configuration -- prefix is in upper-case
2) `io.bootique.config.jackson.JsonNodeConfigurationFactory#findChild` looks for properties under `my` (default config prefix) -- in lower-case

**Comment by andrus** [comment]
Actually the case describe above works. A case that doesn't work requires a Map in the path. As we don't have any guidance as to capitalization of the map keys, unless they are also defined in YAML

**Comment by atomashpolskiy** [comment]
Sorry, but I'm pretty sure that the case that I've described does not work. It can be seen pretty clearly from the code that `io.bootique.config.jackson.JsonNodeConfigurationFactory#findChild` will not find `MyModule` configuration node if its' key in the configuration tree is in upper case (which is precisely the case when it's merged from CLI variable):
```
{
  MY: {
    foo: val
  }
}
```

**Comment by andrus** [comment]
See Bootique_ConfigurationIT.java on branch 133 : https://github.com/bootique/bootique/commit/031b95480985cd74f49cc2c6611cc809d84dad5f

Your case seems to be equivalent to `testConfigEnvVars_NoYaml` , which succeeds. `testConfigEnvVars_Map` is the one that fails.

**Comment by atomashpolskiy** [comment]
It's not equivalent because you use an empty prefix:

```
Bean1 b1 = runtime.getInstance(ConfigurationFactory.class).config(Bean1.class, "");
```

**Comment by andrus** [comment]
Ok, prefix results in a top-level map. So we are both right.

**Comment by atomashpolskiy** [comment]
I guess I'm not being clear enough. Let me explain the issue once again.

Imagine there is an app that is comprised of 3 modules: CayenneModule, JdbcModule, LinkMoveModule. There is a YAML configuration:
```yaml
jdbc:
  ds1:
    # datasource config

cayenne:
  configs:
    # list of configs
  datasource: ds1
```

There is also an environment variable `BQ_LINKMOVE_EXTRACTORSDIR`.

In runtime the aggregate configuration will look like this:
```
{
  jdbc: {
    ds1: { ... }
  },
  cayenne: {
    configs: [ ... ],
    datasource: "ds1"
  },
  LINKMOVE: {
    EXTRACTORSDIR: "/path/to/extractors"
  }
}
```

There isn't any `java.util.Map` involved in this issue. There is an application's configuration tree in which each child node represents configuration for some module.

Now, when `LinkMoveModule` calls `ConfigurationFactory#config(Class, String)` to build an instance of `LmRuntime`, the `io.bootique.config.jackson.JsonNodeConfigurationFactory` will NOT find the configuration node for `LinkMoveModule`, because it will perform the lookup by `linkmove` prefix (which is suggested by default by `ConfigModule`), and the configuration is under `LINKMOVE` key.

Makes sense?

**Comment by andrus** [comment]
Fixed the case of root config prefix ambiguity. Unfortunately this made config prefix for each module case insensitive. From `JsonNodeConfigurationFactory.java`:

```java
// TODO: this also makes YAML prefix case-insensitive, and the whole config more ambiguous, 
// which is less than ideal. Perhaps we can freeze prefix case for YAMLs by starting with a 
// synthetic JsonNode based on the prefix and then overlay CS config (YAML) only then - 
// CI config (vars)?  This will require deep refactoring. Also
// we will need to know the type of the root JsonNode (String vs Object vs List, etc.)
```

Keys in Maps defined via vars will unfortunately stay in uppercase. This is not solved. Perhaps we can better diagnose such cases and print a warning to the users.
