### ISSUE TITLE
pid and stopping an application

### ISSUE THREAD

**Issue by ari** [bootique/bootique#139]
The default shell script in Bootique which starts an application doesn't save a PID file anywhere and therefore it is very difficult to stop an application. Ideally we should be able to pass three commands to the shell script:

* start
* stop
* status

Status will return the status of the application (whether it is running or not) simply by comparing the PID file to the process list from "ps".

**Comment by andrus** [comment]
@ari : we don't ship any shell scripts with Bootique. Do you mean `io.bootique.Bootique` Java class with `main` in it?

**Comment by ari** [comment]
Ah, my bad. I misunderstood where the shell script we were using comes from.

**Comment by ari** [comment]
I was confused because spring-boot includes such a script: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script

But in fact the one in my project comes from gradle: https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt and not from bootique.

The spring-boot one is quite nice.

**Comment by andrus** [comment]
We need to brainstorm on this and other tools. I had it on my TODO list for some time.
