### ISSUE TITLE
Bootique Examples 

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#145]
Purpose of the [Bootique Examples](https://github.com/bootique-examples/) organization to collect examples of the use of bootique modules.

## Missing Examples

Not all modules are present in the organization, so we need to create examples of using missing modules:

- [x] [bootique-undertow](https://github.com/bootique/bootique-undertow)
- [x] [bootique-jetty](https://github.com/bootique/bootique-jetty)
- [x] [bootique-cayenne](https://github.com/bootique/bootique-cayenne)
- [x] [bootique-jdbc](https://github.com/bootique/bootique-jdbc)
- [x] [bootique-jersey-client](https://github.com/bootique/bootique-jersey-client)
- [x] [bootique-linkrest](https://github.com/bootique/bootique-linkrest)
- [x] [bootique-mvc](https://github.com/bootique/bootique-mvc)
- [x] [bootique-swagger](https://github.com/bootique/bootique-swagger)
- [x] [bootique-jersey](https://github.com/bootique/bootique-jersey)
- [x] [bootique-kotlin](https://github.com/bootique/bootique-kotlin)
- [x] [bootique-shiro](https://github.com/bootique/bootique-shiro)
- [x] [bootique-linkmove](https://github.com/bootique/bootique-linkmove)
- [x] [bootique-tapestry](https://github.com/bootique/bootique-tapestry)
- [x] [bootique-jooq](https://github.com/bootique/bootique-jooq)
- [x] [bootique-liquibase](https://github.com/bootique/bootique-liquibase)
- [x] [bootique-flyway](https://github.com/bootique/bootique-flyway)
- [x] [bootique-job](https://github.com/bootique/bootique-job)
- [x] [bootique-kafka-client](https://github.com/bootique/bootique-kafka-client)
- [x] [bootique-logback](https://github.com/bootique/bootique-logback)
- [x] [bootique-jcache](https://github.com/bootique/bootique-jcache)
- [x] [bootique-curator](https://github.com/bootique/bootique-curator)
- [x] [bootique-metrics](https://github.com/bootique/bootique-metrics)
- [x] [bootique-rabbitmq-client](https://github.com/bootique/bootique-rabbitmq-client)

## Cleanup existing examples:

- [x] [bootique-rest-demo](https://github.com/bootique-examples/bootique-rest-demo)
- [x] [bootique-kafka-producer](https://github.com/bootique-examples/bootique-kafka-producer)
- [x] [bootique-kafka-consumer](https://github.com/bootique-examples/bootique-kafka-consumer)
- [x] [bootique-linkrest-demo](https://github.com/bootique-examples/bootique-linkrest-demo)
- [x] [bootique-jobs-demo](https://github.com/bootique-examples/bootique-jobs-demo)

**Comment by andrus** [comment]
Re: bootique-metrics-demo.. The demo is using a [custom DataSourceFactory](https://github.com/bootique-examples/bootique-metrics-demo/tree/master/src/main/java/io/bootique/metrics/demo/ds). It should use one of the standard instrumented DataSource factories, either Tomcat or Hikari.
