### ISSUE TITLE
Simplify/Automate release process

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#149]
Currently release take a lot of time, so some automation required. I think at first place @andrus should describe how currently release done.

**Comment by andrus** [comment]
## Current release procedure

I have a list of projects that I maintain locally (see below). They are sorted by dependency (if a module A has dependency on module B, B is sorted lower than A). For each project on the list the release steps are:

1. Pre-release cleanup. For each project on the list manually change SNAPSHOT dependencies on other Bootique modules to release dependencies. Commit. (This can be done with Maven, I prefer manual though. It is more predictable).

2. Do a Maven release. For each project on the list, run the following sequence. Don't forget `-Pgpg` to add signatures:
```
mvn release:prepare -Pgpg -DautoVersionSubmodules=true
# now manually confirm the release version and the next version when asked by Maven

mvn release:perform -Pgpg

# Now need to cleanup my local copy 
git pull --rebase
```
This places all modules on Bintray. 

3. Login to bintray in the browser, and go and sync the module to Maven Central. Requires typing oss.sonatype.org password in the form each time. This process hangs for ~30 sec (while oss.sonatype.com verifies the artifacts).

## Special cases:

1. When releasing `bootique-bom`, there's an additional step "0" -  remove "SNAPSHOT" for all mentioned modules from its pom.xml and commit.
2. If a module has never been released in the past, we need to request its syncing with Maven Central to be setup by Bintray. This is done via Bintray UI after step 2 and takes anywhere from 0.5 to 8 hours. 

##  Sorted list of projects
bootique
bootique-metrics
bootique-curator
bootique-jcache
bootique-logback
bootique-kafka-client
bootique-rabbitmq-client
bootique-undertow
bootique-jdbc (bootique-metrics)
bootique-jetty (bootique-metrics)
bootique-cayenne (bootique-jdbc, bootique-jcache)
bootique-job (bootique-curator)
bootique-flyway (bootique-flyway)
bootique-liquibase (bootique-jdbc)
bootique-jooq (bootique-jdbc, bootique-logback)
bootique-undertow
bootique-tapestry (bootique-jetty)
bootique-jersey (bootique-jetty)
bootique-linkmove (bootique-jdbc, bootique-cayenne)
bootique-linkrest (bootique-jetty, bootique-jersey, bootique-cayenne, bootique-jdbc)
bootique-jersey-client (bootique-metrics, bootique-jersey - for tests)
bootique-mvc (bootique-jetty, bootique-jersey)
bootique-shiro
bootique-swagger (bootique-jetty, bootique-jersey)
bootique-kotlin
bootique-bom (all)

**Comment by stariy95** [comment]
This one is done in [bootique-tools/release](https://github.com/bootique-tools/release)
