### ISSUE TITLE
Override Bootique module from a user module

### ISSUE THREAD

**Issue by atomashpolskiy** [bootique/bootique#156]
Given the following dependency chain: `application` _--uses-->_ `custom module` _--overrides-->_ `Bootique module`, where each of the components resides in a separate jar, and the custom module 's jar is a reusable artifact shared among many applications, and everything is auto-loaded from the CP, is there any way to eliminate the need to write `override(BootiqueModule.class).with(CustomModule.class)`, when creating the application? The point is that `CustomModule` might be the only version that the user is really interested in using (e.g. it augments standard Bootique services with some behavior, that is required for all applications).

**Comment by andrus** [comment]
The question arose from trying to address the bug described in #157 . This is fixed now, so I assume this one is resolved too?
