### ISSUE TITLE
CLI Options duplicate names check

### ISSUE THREAD

**Issue by ebondareva** [bootique/bootique#173]
Evidently, that options with the same names on CLI don't have a sense. It would be useful to add a strict check for duplication of options' names and trace detailed info for a user. 

**Note:** it shouldn't be forgot - a command also has options. Now intersection of command options' names with CLI options ones isn't checked. The behavior need to be defined futher.  

The issue is connected with: Config CLI options #111.

**Comment by andrus** [comment]
So reiterating the behavior:

* **_(0.24)_ If two standalone options have the same long name, an exception is thrown.**
* _(0.23)_ If two commands have the same long name, an exception is thrown.
* _(0.23)_ If a standalone option and command have the same long name, nothing happens.
* _(0.23)_ If a standalone option and one of the command's options have the same long name, nothing happens.
