### ISSUE TITLE
Module aggregation / define module dependencies.

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#183]
Simple example:

Application that have few modules like: ApiModule, ServiceModule, ModelModule.

And there are following hierarchy:

```
Api
  |
Service
  |
Model
``` 

So currently main will looks like:

```
Bootique
    .app(args)
    .module(ApiModule.class)
    .module(JettyModule.class)
    .module(ModelModule.class)
    .module(CayenneModule.class)
    .module(ServiceModule.class)
    .module(JwtModule.class)
    .exec()
    .exit()
```

So main can getting bigger in real application, and after some time you can find unused modules, or modules usage of unclear.

I propose defining module dependencies explicitly inside `BQModuleProvider`:

```
class MyModuleProvider implements BQModuleProvider {

        @Override
        public Module module() {
            return new MyModule();
        }

        @Override
        public Collection<BQModuleProvider> dependencies() {
            return asList(
                new JettyModuleProvider(), 
                new LogbackModuleProvider()
            );
        }
    }
```

**Comment by andrus** [comment]
Done. Now we may start eating our own dog food, i.e. review our standard modules to add dependency metadata to all of those that have dependencies

**Comment by IRus** [comment]
We rethink this implementation, and I going to change `BQModuleProvider` API. New approach is to change `dependencies` method, so it will return list of `BQModuleProvider` Classes. I'll experiment with this change in #204

**Comment by andrus** [comment]
Decided to abandon explicit module dependency tracking per #340, at least for now
