### ISSUE TITLE
Update Guice to 4.2.0

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#188]
Guice `4.0` released in April 2015! Next version of Guice - `4.1.0`  [released](https://github.com/google/guice/wiki/Guice41) in June 2016.

I tried to simply bump version and run tests, but there are few failed tests. Looks like there are changes around how `ProvisionException` populated with error messages. So to update guice version we need to fix few tests, and try on real world apps that there are no other regressions.

**Comment by andrus** [comment]
It will be really important to upgrade Guice to a version that supports Java 9 properly per https://github.com/google/guice/issues/1085 . Looks like it is coming soon.

**Comment by IRus** [comment]
http://mvnrepository.com/artifact/com.google.inject/guice/4.2.0
