### ISSUE TITLE
Update Jackson to 2.9.5

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#189]
We have outdated version of jackson - 2.9.0. A lot of libraries already using new versions of jackson(typically 2.8, since 2.9 fresh version) so I think we need to update jackson.

**Comment by andrus** [comment]
Need to be very careful with this. This is going to have a ripple effect across all libraries that Bootique supports (Jersey, and more).

**Comment by andrus** [comment]
Updated to 2.9.5. A bunch of module-specific tasks opened to upgrade specific modules.

**Comment by andrus** [comment]
Probably a good idea. In most cases it doesn't matter (as downstream modules get the right version from the core as a transitive dependency), but there are a few that import it explicitly.
