### ISSUE TITLE
Declare dependencies in the standard modules

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#203]
Per #183  we are allowing modules to optionally declare dependencies. This is very helpful in unit tests when we are assembling partial stacks and would prefer not to use "autoLoadModules". So let's declare explicit dependencies across all standard Bootique modules.

**Comment by IRus** [comment]
- [ ] job
- [ ] job-instrumented
- [ ] cayenne
- [ ] cayenne-jcache
- [ ] jdbc-instrumented
- [ ] jetty-metrics
- [ ] jetty-instrumented
- [ ] shiro-jdbc
- [ ] shiro-web
- [ ] linkmove
- [ ] jersey
- [ ] jersey-jackson
- [ ] jersey-client
- [ ] jersey-client-instrumented
- [ ] tapestry
- [ ] liquibase
- [x] flyway
- [x] logback-sentry
- [ ] jooq
- [ ] linkrest
- [ ] mvc
- [ ] mvc-mustache
- [ ] swagger

**Comment by IRus** [comment]
Accidentally committed changes in `bootique-test` to master: https://github.com/bootique/bootique/commit/97f1a3a2a97e1b0f5f3d49ac7db0e527edcaac17. @andrus can you review this commit?

**Comment by andrus** [comment]
The test method looks fine. I am ok with it if it works :)

**Comment by IRus** [comment]
@andrus all modules now has dependencies
