### ISSUE TITLE
JDK9 Compatibility

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#205]
To check that bootique and bootique modules compatible with JDK 9 I started adding `oraclejdk9` to travis build configurations.

**Comment by IRus** [comment]
First issue we found - mockito-core 2.0.31-beta not compatible with java 9, so we update it ti 2.15.0 https://github.com/bootique/bootique-modules-parent/issues/4

**Comment by IRus** [comment]
Now I'm going to update version of `bootique-modules-parent` across all modules:

- [] bootique
- [] bootique-aws
- [] bootique-bom
- [] bootique-cayenne
- [] bootique-curator
- [] bootique-docs
- [] bootique-flyway
- [] bootique-io
- [] bootique-jdbc
- [] bootique-jcache
- [] bootique-jersey
- [] bootique-jersey-client
- [] bootique-jetty
- [] bootique-job
- [] bootique-jooq
- [] bootique-kafka-client
- [] bootique-kotlin
- [] bootique-linkmove
- [] bootique-linkrest
- [] bootique-liquibase
- [] bootique-logback
- [] bootique-metrics
- [] bootique-modules-parent
- [] bootique-mvc
- [] bootique-parent
- [] bootique-rabbitmq-client
- [] bootique-shiro
- [] bootique-swagger
- [] bootique-tapestry
- [] bootique-undertow

**Comment by IRus** [comment]
Incompatible modules:

- [ ] bootique-tapestry
- [ ] bootique-jetty
- [ ] bootique-jersey
- [ ] bootique-jersey-client

**Comment by andrus** [comment]
@IRus Do we have any details on Jetty and Jersey issues with Java 9? (I know about Tapestry, but note these two). Also we just upgraded both [Jetty](https://github.com/bootique/bootique-jetty/issues/76) and [Jersey](https://github.com/bootique/bootique-jersey/issues/38) , so maybe the newer versions are Java 9 compatible?

**Comment by IRus** [comment]
Yes, they are compatible now, so I fixed few issues about javaee modules which thrown out of jdk9 and enable jdk9 build in travis.

**Comment by IRus** [comment]
Closing this issue, since only tapestry module affected https://github.com/bootique/bootique-tapestry/issues/16.

Moving forward with jdk10 support JDK10 Compatibility #222
