### ISSUE TITLE
Cleaning up APIs deprecated since <= 0.25

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#214]
We are approaching 1.0 beta, so need to get aggressive removing deprecated features before we freeze the API. So going to remove everything currently deprecated in the core and across modules.

**Comment by erdinckocaman** [comment]
Jetty version can be upgraded, default version used in Bootique has a "serious" bug - I don't remember what was it now - so I fixed it by updating pom file I used in my app.

**Comment by andrus** [comment]
@erdinckocaman Will look into that. Appreciate if you could find any info on that bug.

**Comment by erdinckocaman** [comment]
I wish I took a note about it. My fault. But I had to update Jetty at that time. I add more info if I can find more about that issue.

**Comment by andrus** [comment]
Done for BQ core. Will open separate tasks for other modules.

**Comment by erdinckocaman** [comment]
I found details about my problem at this link https://github.com/eclipse/jetty.project/issues/1627
It is fixed at version 9.4. The problem was happening when there was too much load on Jetty server.

**Comment by andrus** [comment]
Thanks. This will be tracked under bootique-jetty: https://github.com/bootique/bootique-jetty/issues/76
