### ISSUE TITLE
Bootique always creates guice injector in DEVELOPMENT stage  

### ISSUE THREAD

**Issue by akoyro** [bootique/bootique#223]
Bootique always creates Guice injector in DEVELOPMENT stage  
`io.bootique.Bootique.createInjector():486` 

But this framework has a few stages, see these links:
- https://github.com/google/guice/wiki/Bootstrap 
- https://github.com/google/guice/wiki/Scopes

for example in PRODUCTION stage all Singleton  services will  have 'eager' initialisation, not lazy.

may be it can be useful to have a possibility to configure the injector stage for cases 
where I need to run a few background processes: for example not only jetty server, I could create 
'self-started' singleton, and don't need to implement some special default command which starts two background processes.

**Comment by andrus** [comment]
This was discussed before (though I think the discussion was offline) . A possibility of Guice "modes" have no bearing on Bootique and should be ignored. It is designed to be started with lazy initialization. 

Regarding background processes, BQ 0.25 has an explicit feature to do that. You still need at least one command to run (it can be a default command, not visible in the help). But it can start multiple processes. See for instance "Command Improvements" section [here](https://blog.bootique.io/the-state-of-bootique-early-2018-part-1-ed6806d9c99a). The example is based on Jetty ServerCommand, but it applies to any command. 

```java
CommandDecorator extraCommands = CommandDecorator
    .alsoRun(ScheduleCommand.class);

BQCoreModule.extend(binder)
    .decorateCommand(ServerCommand.class, extraCommands);
```

**Comment by akoyro** [comment]
Thank you Andrus for this explanation.  I will use this approach. I am closing this issue.

**Comment by IRus** [comment]
> This was discussed before 

https://groups.google.com/forum/#!topic/bootique-user/VxXMf9wY6CQ
