### ISSUE TITLE
Add copyright to all sources

### ISSUE THREAD

**Issue by stariy95** [bootique/bootique#226]
Add copyright headers to all source files in all bootique modules:

- [x] [bootique](https://github.com/bootique/bootique)
- [x] [bootique-aws](https://github.com/bootique/bootique-aws)
- [x] [bootique-bom](https://github.com/bootique/bootique-bom)
- [x] [bootique-cayenne](https://github.com/bootique/bootique-cayenne)
- [x] [bootique-curator](https://github.com/bootique/bootique-curator)
- [x] [bootique-cxf](https://github.com/bootique/bootique-cxf)
- [x] [bootique-di](https://github.com/bootique/bootique-di)
- [x] [bootique-flyway](https://github.com/bootique/bootique-flyway)
- [x] [bootique-jcache](https://github.com/bootique/bootique-jcache)
- [x] [bootique-jdbc](https://github.com/bootique/bootique-jdbc)
- [x] [bootique-jersey](https://github.com/bootique/bootique-jersey)
- [x] [bootique-jersey-client](https://github.com/bootique/bootique-jersey-client)
- [x] [bootique-jetty](https://github.com/bootique/bootique-jetty)
- [x] [bootique-job](https://github.com/bootique/bootique-job)
- [x] [bootique-jooq](https://github.com/bootique/bootique-jooq)
- [x] [bootique-kafka-client](https://github.com/bootique/bootique-kafka-client)
- [x] [bootique-kotlin](https://github.com/bootique/bootique-kotlin)
- [x] [bootique-linkmove](https://github.com/bootique/bootique-linkmove)
- [x] [bootique-linkrest](https://github.com/bootique/bootique-linkrest)
- [x] [bootique-liquibase](https://github.com/bootique/bootique-liquibase)
- [x] [bootique-logback](https://github.com/bootique/bootique-logback)
- [x] [bootique-metrics](https://github.com/bootique/bootique-metrics)
- [x] [bootique-modules-parent](https://github.com/bootique/bootique-modules-parent)
- [x] [bootique-mvc](https://github.com/bootique/bootique-mvc)
- [x] [bootique-parent](https://github.com/bootique/bootique-parent)
- [x] [bootique-rabbitmq-client](https://github.com/bootique/bootique-rabbitmq-client)
- [x] [bootique-shiro](https://github.com/bootique/bootique-shiro)
- [x] [bootique-swagger](https://github.com/bootique/bootique-swagger)
- [x] [bootique-tapestry](https://github.com/bootique/bootique-tapestry)
- [x] [bootique-undertow](https://github.com/bootique/bootique-undertow)

**Comment by andrus** [comment]
I applied the PR. A few minor points:

* "the" should be removed from this text: "Licensed to ~~the~~ ObjectStyle LLC"
* Remove paragraph indentation before "Licensed"
