### ISSUE TITLE
Upgrade bootique and core modules to bootique-modules-parent:0.11

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#232]

**Comment by IRus** [comment]
@andrus all modules except bootique-jersey-client (https://github.com/bootique/bootique-jersey-client/issues/38) and bootique-tapestry builds on jdk11. Maybe we can remove `allow_failures: openjdk11` from travis config?

**Comment by andrus** [comment]
Yes, for those that don't fail, lets disallow future failures.
