### ISSUE TITLE
Default value for command options

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#233]
For example I define simple command with default value for command option:

```
class TestCommandDefaultOption extends CommandWithMetadata {
    public final static String OPT = "opt";

    public TestCommandDefaultOption() {
        super(CommandMetadata.builder("testCommandDefaultOption")
                .addOption(OptionMetadata.builder(OPT).defaultValue("optValue").build()));
    }

    @Override
    public CommandOutcome run(Cli cli) {
        return CommandOutcome.succeeded();
    }
}
```

I expecting that if I'm not pass any value for option `opt` I will get `optValue` for `cli.optionString` call, but instead I got `null`.

**Comment by IRus** [comment]
Test case available in https://github.com/bootique/bootique/tree/issue-233

**Comment by IRus** [comment]
@andrus Is it actually bug?

**Comment by elena-bondareva** [comment]
Yes, this is a bug.

**Comment by stariy95** [comment]
Here is small bug overview for the history. Default value in `OptionMetadata` was used only as `configPath` default and nowhere else. 
Fix changes this behavior and now default value used as stated, i.e. as default value when option is present but no value provided for that option.
