### ISSUE TITLE
Consider using picocli

### ISSUE THREAD

**Issue by remkop** [bootique/bootique#260]
Unsure if this has been considered before, but it may be interesting to replace joptsimple with [picocli](https://picocli.info).

There could be several benefits, depending on whether this is limited to an internal change or whether you want to go further.

End user benefits:

* usage help with [ANSI colors and styles](https://picocli.info/#_ansi_colors_and_styles). This doesn’t just look good, it also reduces the cognitive load on end users: the contrast make important information like commands, options, and parameters stand out from the surrounding text.
* [@-files](https://picocli.info/#AtFiles) to load arguments from files

Maintenance benefits:
* built-in support for [subcommands](https://picocli.info/#_subcommands): less code to maintain
* built-in support for [Dependency Injection](https://picocli.info/#_dependency_injection)
* built-in support for [interactive password options](https://picocli.info/#_interactive_password_options)
* actively [maintained](https://github.com/remkop/picocli) and extensive documentation

Depending on how much you like this idea, you could consider allowing users to create custom bootique-based CLI applications using the picocli API directly, similar to [Micronaut's approach](https://docs.micronaut.io/latest/guide/index.html#commandLineApps).

Thoughts?

**Comment by andrus** [comment]
Thanks for the pointer. In fact we considered replacing jopt with our own CLI parser as a part of the general effort to remove 3rd party dependencies.  Will certainly take a look at Picocli. We do need something more advanced.

**Comment by remkop** [comment]
Ok, interesting. You may like the fact that picocli is in a [single source file](https://github.com/remkop/picocli/wiki/FAQ) so applications also have the option to include it as source to avoid the external dependency.

But take a look at whether picocli's functionality is attractive or whether you would rather develop this in-house. Are you mainly interested in using this internally in Bootique or are you considering offering/expanding an external API for applications to create Bootique-based CLI applications?

Let me know if I can help. -Remko

**Comment by remkop** [comment]
Update: picocli 4.0 adds some features that may be of interest:

* repeatable nested [argument groups](https://picocli.info/#_argument_groups)
* [negatable options](https://picocli.info/#_negatable_options) ("no-")
* [execute](https://picocli.info/#execute) API improves exit code support and reduces boilerplate code
* improved support for [GraalVM native images](https://picocli.info/#_graalvm_native_images)

... and more. See the [4.0 release notes](https://github.com/remkop/picocli/releases/tag/v4.0.0) for more detail.

I'd be happy to help if there is interest.

**Comment by andrus** [comment]
We still haven't got around to reworking options handling (that's probably Bootique 4.0). But the consensus is that we are not going to add any new third-party dependencies to the Bootique core, and will be working towards getting rid of most of the current ones.
