### ISSUE TITLE
Support specifying config key for "-H"

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#267]
"-H" is a useful help option that prints all the supported configuration structure. Let's allow to narrow it down by providing an argument that is a config key to this switch. E.g.:

```
# Current behavior - print all configs
java -jar myapp.jar -H

# Additional new behavior - print config tree for JerseyClient module:
java -jar myapp.jar -H jerseyclient
```

**Comment by princejha95** [comment]
Hi, I am interested in contributing in this project. Can you please guide me from where should i start ?

**Comment by andrus** [comment]
> Hi, I am interested in contributing in this project. Can you please guide me from where should i start ?

Hi, 
Posting this request as a comment for an unrelated task in the bug tracker is not a good idea.

I suggest you post a message on [Bootique forum](https://groups.google.com/forum/#!forum/bootique-user), introduce yourself and explain why you are interested in Bootique?

**Comment by princejha95** [comment]
HI Andrus,

My apologies for posting the request in the bug tracker. I have posted the
request in the forum with my introduction and reason for being interested
in Bootique.

Thanks,
Prince
