### ISSUE TITLE
bootique-test integration with junit5

### ISSUE THREAD

**Issue by aarrsseni** [bootique/bootique#271]
Now bootique-test depends from junit4.
To use bootique-test with junit5 user need to add junit-vintage dependency.
Now junit5 provides extension model instead of rule model. So it will be great if bootique-test will support new features of junit5.

**Comment by aarrsseni** [comment]
Here is PR for it https://github.com/bootique/bootique/pull/272

**Comment by andrus** [comment]
While there's still work to be done in downstream modules to port to JUnit 5, the core module is ready.
