### ISSUE TITLE
Ambiguos "Bootique.module(..)" methods

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#288]
`Bootique.module(..)` can take a `Class<? extends BQModule>`, `BQModule` and `BQModuleProvider`. With the introduction of `BaseModule` [in 1.1](https://github.com/bootique/bootique/issues/262) that is both a module and a provider, the last two variants become ambiguous and require an explicit cast. Let's rename `Bootique.module(BQModuleProvider)` to `Bootique.moduleProvider(BQModuleProvider)`. Do the same renaming in `BQTestRuntimeBuilder`

## Upgrade Notes

`Bootique.module(BQModuleProvider)` and `BQTestRuntimeBuilder.module(BQModuleProvider)` will no longer be available. If you get a compilation error, replace both these methods with `moduleProvider`.

**Comment by championjing** [comment]
unsubscribe


| |
championjing
|
|
championjing@163.com
|
签名由网易邮箱大师定制
On 5/10/2020 14:15，Andrus Adamchik<notifications@github.com> wrote：

Closed #288.
