### ISSUE TITLE
An Inefficient Usage of Java Collections

### ISSUE THREAD

**Issue by FastAtlas** [bootique/bootique#312]
Hi,
We find that the List `actualModules` allocated at line 49 in the file `bootique-junit5/src/main/java/io/bootique/junit5/BQRuntimeChecker.java` is only used to check whether an element is stored in the container. The method `contains` at line 61 runs in linear time complexity.

To achieve the same functionality, maybe a `HashSet` can provide a more efficient implementation. We can just construct a `HashSet` from the list directly at line 49 and then utilize the `contains` method of `HashSet` to perform the searching in amortized constant time.

We discovered this inefficient usage of containers by our tool Ditto. The patch is submitted in #311. Could you please check and accept it? We have tested the patch on our PC. The patched program works well.

Bests

Ditto

**Comment by andrus** [comment]
Thanks for pointing it out. I just committed a cleaner implementation. I didn't use the PR, as it creates an extra collection (converts a Stream into a List and the List to a Set).
