### ISSUE TITLE
Code: Text is larger than text box

### ISSUE THREAD

**Issue by Natallika** [bootique/bootique#50]
**Environment**:
Android 4.4.4 Chrome v48 
iPhone 6 iOS 8.1 
iPad iOS 9.2.1 Chrome 48.0, Safari

**Steps**:
Get Started and Documentation pages - 1.png is attached.

![1](https://cloud.githubusercontent.com/assets/6305702/14208123/73e78668-f826-11e5-943e-89d991867187.png)

**Comment by IRus** [comment]
Since this issue isn't in scope of bootique project itself it moved to site repository.
